### ISSUE TITLE
Provide matching Slingshot `Repair` data

### ISSUE THREAD

**Issue by orvn** [filecoin-project/slingshot-stats#10]
Similar to https://github.com/filecoin-project/slingshot-stats/issues/9, but for the _Slingshot Repair_, which is performed in lockstep with [Estuary](https://estuary.tech).

In this case, deals that match the following two criteria are needed:
1. Client address is one of Estuary's repair addresses
2. CIDs match those on a hard coded list (≈ 20k deals) that is shared between the Slingshot app and `slingshot-stats`

`slingshot-stats` will serve up an array of deals with the that match the criteria in the following schema

```ts
[ 
  {
    deal_id: string,
    address: string,
    miner_id: string,
    payload_cid: string, // CID v1 “bafy”
    piece_cid: string,
    data_size: int, // bytes
    deal_start_epoch: int,
    deal_end_epoch: int,
    recovery: enum // 1: restore, 2: repair
  } 
]

```

For restore data, the `recovery` flag is always `1`

**Comment by justanothersynth** [comment]
Updated deal structure below:

```js
[ 
  {
    deal_id: string,
    client_address: string,
    miner_id: string,
    payload_cid: string, // CID v1 “bafy”
    piece_cid: string,
    data_size: int, // bytes
    deal_start_epoch: int,
    deal_end_epoch: int,
    recovery: enum, // 1: restore, 2: repair
  } 
]
```
