### ISSUE TITLE
Provide matching Slingshot `Restore` data

### ISSUE THREAD

**Issue by orvn** [filecoin-project/slingshot-stats#9]
For the _Slingshot Restore_ initiative, some matching deal data is required from the chain in an effort to restore what was terminated.

`slingshot-stats` is provided an array of IDs and addresses from a _slingshot.filecoin.io_ endpoint

```ts
[ 
  {
    client_id: string, // a unique key, essentially a project id
    client_address: string,
    dataset_slug: string,
    dataset_name: string,
    client_name: string,
    client_slack_handle: string
  } 
]

```

In response, `slingshot-stats` will serve up an array of deals with the following schema, based on deals that match on-chain

```ts
[ 
  {
    deal_id: string,
    restore_id: string,
    address: string, // client wallet address
    miner_id: string,
    payload_cid: string, // CID v1 “bafy”
    piece_cid: string,
    data_size: int, // bytes
    deal_start_epoch: int,
    deal_end_epoch: int,
    recovery: enum // 1: restore, 2: repair
  } 
]
```

For restore data, the `recovery` flag is always `2`

The Slingshot App gets this endpoint/file on a cron, processes and caches the data.

**Comment by justanothersynth** [comment]
Updated deal structure below:

```js
[ 
  {
    deal_id: string,
    client_address: string,
    miner_id: string,
    payload_cid: string, // CID v1 “bafy”
    piece_cid: string,
    data_size: int, // bytes
    deal_start_epoch: int,
    deal_end_epoch: int,
    recovery: enum, // 1: restore, 2: repair
  } 
]
```

**Comment by justanothersynth** [comment]
Closing issue because Restore data is flowing well 👌🏼
